backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: src/img/portfolio
public_folder: /img
collections:
  - name: "portfolio" # Used in routes, e.g., /admin/collections/blog
    label: "Portfolio" # Used in the UI
    folder: "src/markdown/portfolio" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Page", name: "page", widget: "hidden", default: "portfolio"}
      - {label: "Best", name: "best", widget: "boolean"}
      - {label: "Landscape", name: "landscape", widget: "boolean"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Location (GBR,JPN, etc)", name: "location", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}