backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: src/img
public_folder: /static
collections:
  - name: "portfolio"
    label: "Portfolio"
    folder: "src/markdown/portfolio"
    create: true
    identifier_field: name
    fields:
      - {label: "Page", name: "page", widget: "hidden", default: "portfolio"}
      - {label: "Best", name: "best", widget: "boolean"}
      - {label: "Landscape", name: "landscape", widget: "boolean"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Location", name: "location", widget: "string", hint: 'GBR,JPN, etc'}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "blog"
    label: "Blog"
    folder: "src/markdown/blog" 
    create: true 
    identifier_field: title
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Path", name: "path", widget: "string", hint: "blog/same-as-title"}
      - {label: "Locale", name: "locale", widget: "select", options: ["en", "jp"]}
      - {label: "Description", name: "SEO", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}
  - name: "store"
    label: "Store"
    folder: "src/markdown/store" 
    create: true 
    identifier_field: title
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "desc", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Main image", name: "main", widget: "image"}
      - label: "Images"
        name: "images"
        widget: "list"
        summary: '{{fields.image}}'
        field: {label: Image, name: image, widget: image}
      - label: "Products"
        name: "products"
        widget: "list"
        summary: '{{fields.title}}'
        fields: 
          - {label: "SKU", name: "sku", widget: "string"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Type", name: "type", widget: "string"}
          - {label: "Size", name: "size", widget: "string"}
          - {label: "Price", name: "price", widget: "number"}
      - {label: "Full image", name: "fullImage", widget: "string", hint: "https://drive.google.com/uc?id=<DRIVE_LINK_IMAGE_ID>"}
      - {label: "Path", name: "path", widget: "string", hint: "prints/same-as-title"}
      - {label: "Locale", name: "locale", widget: "select", options: ["en", "jp"]}
      - {label: "Content", name: "body", widget: "markdown"}
  - name: "general"
    label: "General"
    folder: "src/markdown/general" 
    create: true 
    identifier_field: page
    fields: 
      - {label: "Page", name: "page", widget: "string"}
      - {label: "Type", name: "type", widget: "string"}
      - {label: "Locale", name: "locale", widget: "select", options: ["en", "jp"]}
      - {label: "Content", name: "body", widget: "markdown"}

  - name: "intl"
    label: "intl"
    extension: "json"
    editor:
      preview: false
    files:
      - file: "src/intl/en.json"
        label: "en"
        name: "en"
        fields:
          - label: 'main'
            name: 'main'
            widget: 'object'
            fields:
                - { label: 'tab', name: 'tab', widget: 'string' }
          - label: 'main'
            name: 'main'
            widget: 'object'
            fields:
                - { label: 'title', name: 'title', widget: 'string' }
                - { label: 'names', name: 'names', widget: 'string' }
                - { label: 'desc', name: 'desc', widget: 'string' }
                - { label: 'portfolio', name: 'portfolio', widget: 'string' }
                - { label: 'blog', name: 'blog', widget: 'string' }
                - { label: 'prints', name: 'prints', widget: 'string' }
                - { label: 'contact', name: 'contact', widget: 'string' }
          - label: 'about'
            name: 'about'
            widget: 'object'
            fields:
                - { label: 'title', name: 'title', widget: 'string' }
                - { label: '1', name: '1', widget: 'string' }
                - { label: '2', name: '2', widget: 'string' }
                - { label: '3', name: '3', widget: 'string' }
                - { label: '4', name: '4', widget: 'string' }
                - { label: '5', name: '5', widget: 'string' }
                - { label: 'contact', name: 'contact', widget: 'string' }
          - label: 'blog'
            name: 'blog'
            widget: 'object'
            fields:
                - { label: 'back', name: 'back', widget: 'string' }
                - { label: 'authorDesc', name: 'authorDesc', widget: 'string' }
                - { label: 'cat', name: 'cta', widget: 'string' }
          - label: 'store'
            name: 'store'
            widget: 'object'
            fields:
                - { label: 'back', name: 'back', widget: 'string' }
                - { label: 'date', name: 'date', widget: 'string' }
                - { label: 'buy', name: 'buy', widget: 'string' }
                - { label: 'selectCountry', name: 'selectCountry', widget: 'string' }
                - { label: 'successMessage', name: 'successMessage', widget: 'string' }
                - { label: 'contactUs', name: 'contactUs', widget: 'string' }
          - label: 'signup'
            name: 'signup'
            widget: 'object'
            fields:
                - { label: 'subscribe', name: 'subscribe', widget: 'string' }
                - { label: 'title', name: 'title', widget: 'string' }
          - label: 'contact'
            name: 'contact'
            widget: 'object'
            fields:
                - { label: 'title', name: 'title', widget: 'string' }
                - { label: 'name', name: 'name', widget: 'string' }
                - { label: 'email', name: 'email', widget: 'string' }
                - { label: 'invalidEmail', name: 'invalidEmail', widget: 'string' }
                - { label: 'success', name: 'success', widget: 'string' }
                - { label: 'message', name: 'message', widget: 'string' }
                - { label: 'submit', name: 'submit', widget: 'string' }
      - file: "src/intl/jp.json"
        label: "jp"
        name: "jp"
        fields:
          - label: 'main'
            name: 'main'
            widget: 'object'
            fields:
                - { label: 'tab', name: 'tab', widget: 'string' }
          - label: 'main'
            name: 'main'
            widget: 'object'
            fields:
                - { label: 'title', name: 'title', widget: 'string' }
                - { label: 'names', name: 'names', widget: 'string' }
                - { label: 'desc', name: 'desc', widget: 'string' }
                - { label: 'portfolio', name: 'portfolio', widget: 'string' }
                - { label: 'blog', name: 'blog', widget: 'string' }
                - { label: 'prints', name: 'prints', widget: 'string' }
                - { label: 'contact', name: 'contact', widget: 'string' }
          - label: 'about'
            name: 'about'
            widget: 'object'
            fields:
                - { label: 'title', name: 'title', widget: 'string' }
                - { label: '1', name: '1', widget: 'string' }
                - { label: '2', name: '2', widget: 'string' }
                - { label: '3', name: '3', widget: 'string' }
                - { label: '4', name: '4', widget: 'string' }
                - { label: '5', name: '5', widget: 'string' }
                - { label: 'contact', name: 'contact', widget: 'string' }
          - label: 'blog'
            name: 'blog'
            widget: 'object'
            fields:
                - { label: 'back', name: 'back', widget: 'string' }
                - { label: 'authorDesc', name: 'authorDesc', widget: 'string' }
                - { label: 'cat', name: 'cta', widget: 'string' }
          - label: 'store'
            name: 'store'
            widget: 'object'
            fields:
                - { label: 'back', name: 'back', widget: 'string' }
                - { label: 'date', name: 'date', widget: 'string' }
                - { label: 'buy', name: 'buy', widget: 'string' }
                - { label: 'selectCountry', name: 'selectCountry', widget: 'string' }
                - { label: 'successMessage', name: 'successMessage', widget: 'string' }
                - { label: 'contactUs', name: 'contactUs', widget: 'string' }
          - label: 'signup'
            name: 'signup'
            widget: 'object'
            fields:
                - { label: 'subscribe', name: 'subscribe', widget: 'string' }
                - { label: 'title', name: 'title', widget: 'string' }
          - label: 'contact'
            name: 'contact'
            widget: 'object'
            fields:
                - { label: 'title', name: 'title', widget: 'string' }
                - { label: 'name', name: 'name', widget: 'string' }
                - { label: 'email', name: 'email', widget: 'string' }
                - { label: 'invalidEmail', name: 'invalidEmail', widget: 'string' }
                - { label: 'success', name: 'success', widget: 'string' }
                - { label: 'message', name: 'message', widget: 'string' }
                - { label: 'submit', name: 'submit', widget: 'string' }