backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: src/img
public_folder: /static
collections:
  - name: "portfolio"
    label: "Portfolio"
    folder: "src/markdown/portfolio"
    create: true
    identifier_field: name
    fields:
      - {label: "Page", name: "page", widget: "hidden", default: "portfolio"}
      - {label: "Best", name: "best", widget: "boolean"}
      - {label: "Landscape", name: "landscape", widget: "boolean"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Location", name: "location", widget: "string", hint: 'GBR,JPN, etc'}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "blog"
    label: "Blog"
    folder: "src/markdown/blog" 
    create: true 
    identifier_field: title
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Path", name: "path", widget: "string", hint: "blog/same-as-title"}
      - {label: "Locale", name: "locale", widget: "select", options: ["en", "jp"]}
      - {label: "Description", name: "SEO", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}
  - name: "store"
    label: "Store"
    folder: "src/markdown/store" 
    create: true 
    identifier_field: title
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "desc", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Main image", name: "main", widget: "image"}
      - label: "Images"
        name: "images"
        widget: "list"
        summary: '{{fields.image}}'
        field: {label: Image, name: image, widget: image}
      - label: "Products"
        name: "products"
        widget: "list"
        summary: '{{fields.title}}'
        fields: 
          - {label: "SKU", name: "sku", widget: "string"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Type", name: "type", widget: "string"}
          - {label: "Size", name: "size", widget: "string"}
          - {label: "Price", name: "price", widget: "number"}
      - {label: "Full image", name: "fullImage", widget: "string", hint: "https://drive.google.com/uc?id=<DRIVE_LINK_IMAGE_ID>"}
      - {label: "Path", name: "path", widget: "string", hint: "prints/same-as-title"}
      - {label: "Locale", name: "locale", widget: "select", options: ["en", "jp"]}
      - {label: "Content", name: "body", widget: "markdown"}
  - name: "general"
    label: "General"
    folder: "src/markdown/general" 
    create: true 
    identifier_field: page
    fields: 
      - {label: "Page", name: "page", widget: "string"}
      - {label: "Type", name: "type", widget: "string"}
      - {label: "Locale", name: "locale", widget: "select", options: ["en", "jp"]}
      - {label: "Content", name: "body", widget: "markdown"}
  - name: "intl"
    label: "intl"
    extension: "json"
    editor:
      preview: false

    files:
      - file: "src/intl/en.json"
        label: "en"
        name: "en"
        fields:
          - { name: body, label: Body, widget: code }
      - file: "src/intl/jp.json"
        label: "jp"
        name: "jp"
        fields:
          - { name: body, label: Body, widget: code }